# Generated by Django 4.1.5 on 2023-04-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='expected_occupancy',
            field=models.IntegerField(default=50),
        ),
    ]
